server:
  port: 8088

spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}

web:
  upload-path: C:/Hpsy/

#关闭thymeleaf缓存
spring:
  thymeleaf:
    cache: false
    #去掉thymeleaf的严格的模板校验
    mode: HTML5
    encoding: UTF-8

spring:
    datasource:
        name: bbs
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：监控统计用的filter:stat日志用的filter:log4j防御sql注入的filter:wall
          driver-class-name: com.mysql.jdbc.Driver
          #基本属性
          url: jdbc:mysql://localhost:3306/bbs?useUnicode=true&characterEncoding=utf8
          username: bbs
          password: "000000" #加引号保证准确
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
          stat-view-servlet:
            enabled: true
            url-pattern: "/druid/*"
            login-username: admin
            login-password: admin
          web-stat-filter:
            enabled: true
            url-pattern: "/*"
            exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
          filter:
            stat:
              db-type: mysql
              log-slow-sql: true
              slow-sql-millis: 2000

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.cn.BBSAutoRelay.model

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

#易码账号
ym:
  username: xiaoyouzi
  password: chenning
  token: 007217998e68856a5a9c22d2692e11a75118981b